### PR TITLE
remove Python2 crumbs

### PR DESCRIPTION
**Pull request by a-detiste**

### CODE REVIEW

**Comment by stkw0** [comment]
Thanks!

**Comment by a-detiste** [comment]
I've uploaded this nice maintenance fork in Debian right now.

I've kept this bug for later: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1063610

See you

**Comment by stkw0** [comment]
Thanks for the heads-up! In Gentoo right now there are no plans to remove p7zip, but eventually we will face the same problem. 
For similar bugs affecting, feel free to open an issue. Even if it's a packaging issue (as probably more distros are or will be affected).

**Comment by a-detiste** [comment]
Today I'm busy with removing Nose ;-) yup another day

**Pull request merged**
